/* KHMER GAME V3 — Lerak visual + 3:00/2s clock + 30s Bot fallback */
(function(){
const MAIN=180000,INC=2000,MATCH=30;let w=MAIN,b=MAIN,last=null,clock=null,match=null,player=null,busy=false;
const $=id=>document.getElementById(id),cells=()=>[...document.querySelectorAll('#board .cell')];
const side=()=>{const t=$('turn')?.textContent||'';return t.includes('ខ្មៅ')?'black':t.includes('ស')?'white':null};
const fmt=ms=>{const s=Math.max(0,Math.ceil(ms/1000)),m=Math.floor(s/60),x=s%60;return String(m).padStart(2,'0')+':'+String(x).padStart(2,'0')};
function style(){if($('lerakV3Style'))return;const s=document.createElement('style');s.id='lerakV3Style';s.textContent=`
.lerak-clock{display:grid;grid-template-columns:1fr auto 1fr;gap:7px;align-items:center;margin:8px 0}.lerak-clock .clock{border:1px solid var(--line);border-radius:14px;padding:8px;text-align:center;background:linear-gradient(180deg,#241b12,#111114)}.lerak-clock small{display:block;color:var(--muted);font-size:9px}.lerak-clock b{display:block;color:var(--gold2);font:800 24px/1.1 system-ui;letter-spacing:1px}.lerak-clock .active{border-color:#d7ad58;box-shadow:0 0 0 2px #d7ad5822}.lerak-clock .danger b{color:#ff6666}.clock-mode{font:700 9px system-ui;color:var(--muted);text-align:center}.bot-notice{margin:7px 0;padding:9px;border:1px solid var(--line);border-radius:12px;background:#ffffff05;color:var(--muted);font-size:9px;text-align:center}
#board .piece{position:relative!important;width:76%!important;height:76%!important;border-radius:50%!important;display:flex!important;align-items:center!important;justify-content:center!important;font-size:clamp(22px,7vw,44px)!important;font-weight:900!important;border:3px solid #4a2814!important;box-shadow:inset 5px 5px 10px #fff7,inset -8px -9px 13px #0008,0 5px 7px #0009!important;overflow:hidden!important;z-index:2!important}#board .piece:before{content:'';position:absolute;inset:7%;border-radius:50%;background:repeating-linear-gradient(18deg,#0000 0 7px,#0002 8px 10px);mix-blend-mode:multiply}#board .piece:after{content:'';position:absolute;left:13%;top:8%;width:30%;height:20%;border-radius:50%;background:#fff8;filter:blur(2px)}#board .piece.whitePiece{background:radial-gradient(circle at 30% 22%,#fff9e8 0 10%,#efcf8b 24%,#b87730 63%,#713b1b)!important;color:#4a2815!important;text-shadow:0 1px #fff8}.piece.blackPiece{background:radial-gradient(circle at 30% 22%,#d0a269 0 9%,#76421f 28%,#3b1d0c 68%,#140903)!important;color:#f5d48b!important;text-shadow:0 2px 2px #000}.piece{font-size:0!important}
`;document.head.appendChild(s)}
function inject(){const a=$('gameArea'),i=a?.querySelector('.lerak-info');if(!i)return;style();if(!$('lerakClock')){const x=document.createElement('div');x.id='lerakClock';x.className='lerak-clock';x.innerHTML='<div id="lcw" class="clock"><small>⚪ ភាគីស</small><b>03:00</b></div><div class="clock-mode">3:00 + 2s</div><div id="lcb" class="clock"><small>⚫ ភាគីខ្មៅ</small><b>03:00</b></div>';i.after(x)}if(!$('botNotice')){const n=document.createElement('div');n.id='botNotice';n.className='bot-notice';n.textContent='🌐 រង់ចាំអ្នកលេងពិត 30 វិនាទី… បើគ្មាន នឹងដាក់ 🤖 Bot';a.prepend(n)}}
function paint(){inject();const a=$('lcw'),z=$('lcb');if(!a||!z)return;a.querySelector('b').textContent=fmt(w);z.querySelector('b').textContent=fmt(b);const t=side();a.classList.toggle('active',t==='white');z.classList.toggle('active',t==='black');a.classList.toggle('danger',w<=30000);z.classList.toggle('danger',b<=30000)}
function startClock(){clearInterval(clock);w=MAIN;b=MAIN;last=side();let prev=Date.now();clock=setInterval(()=>{const t=side(),now=Date.now(),dt=now-prev;prev=now;if(t==='white')w=Math.max(0,w-dt);else if(t==='black')b=Math.max(0,b-dt);if(t&&last&&t!==last){if(last==='white')w+=INC;else b+=INC;last=t}paint();if(w<=0||b<=0){clearInterval(clock);try{gameOver=true}catch(e){}try{message('⏱️ '+(w<=0?'ភាគីខ្មៅ':'ភាគីស')+' ឈ្នះដោយពេលវេលាអស់។')}catch(e){}}},100);paint()}
function botMove(){if(busy||!player||side()===player)return;busy=true;setTimeout(()=>{const s=side(),sel=s==='white'?'.whitePiece':'.blackPiece';const pcs=cells().filter(c=>c.querySelector('.piece'+sel)).sort(()=>Math.random()-.5);let ok=false;for(const p of pcs){p.click();const mv=cells().filter(c=>c.classList.contains('move')||c.classList.contains('move-choice'));if(mv.length){mv[Math.floor(Math.random()*mv.length)].click();ok=true;break}}busy=false;if(!ok)inject()},550)}
function startMatch(){clearInterval(match);let n=MATCH;match=setInterval(()=>{n--;const x=$('botNotice');if(x)x.textContent=n?`🌐 រង់ចាំអ្នកលេងពិត ${n} វិនាទី…`:'🤖 មិនមានអ្នកលេងពិត — Bot ចូលលេងជំនួស';if(n<=0){clearInterval(match);player=side()||'white';setTimeout(botMove,700)}},1000)}
function observe(){inject();const board=$('board');if(!board){setTimeout(observe,200);return}let started=false;const check=()=>{inject();if(cells().length>=64&&!started){started=true;player=side()||'white';startClock();startMatch()}if(started&&side()&&side()!==player)setTimeout(botMove,400);paint()};new MutationObserver(check).observe(board,{childList:true,subtree:true});const t=$('turn');if(t)new MutationObserver(check).observe(t,{childList:true,subtree:true,characterData:true});check()}
const wait=setInterval(()=>{if($('gameArea')&&$('board')&&$('turn')){clearInterval(wait);observe()}},200);
})();
